### ISSUE TITLE
Got a fatal error while trying to check directory

### ISSUE THREAD

**Issue by akost** [sstalle/php7cc#1]
I am trying to check my project folder and got an error:

I run: `php bin/php7cc.php /var/www/example.com/ php`

### Error: 

```
PHP Catchable fatal error:  Argument 1 passed to Sstalle\php7cc\Iterator\ExtensionFilteringRecursiveIterator::__construct() must be an instance of RecursiveDirectoryIterator, string given in /home/vagrant/php7cc/src/Iterator/ExtensionFilteringRecursiveIterator.php on line 17

PHP Stack trace:
PHP   1. {main}() /home/vagrant/php7cc/bin/php7cc.php:0
PHP   2. Symfony\Component\Console\Application->run() /home/vagrant/php7cc/bin/php7cc.php:7
PHP   3. Symfony\Component\Console\Application->doRun() /home/vagrant/php7cc/vendor/symfony/console/Symfony/Component/Console/Application.php:124
PHP   4. Symfony\Component\Console\Application->doRunCommand() /home/vagrant/php7cc/vendor/symfony/console/Symfony/Component/Console/Application.php:193
PHP   5. Symfony\Component\Console\Command\Command->run() /home/vagrant/php7cc/vendor/symfony/console/Symfony/Component/Console/Application.php:889
PHP   6. Sstalle\php7cc\Infrastructure\PHP7CCCommand->execute() /home/vagrant/php7cc/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:253
PHP   7. Sstalle\php7cc\PathChecker->check() /home/vagrant/php7cc/src/Infrastructure/PHP7CCCommand.php:71
PHP   8. Sstalle\php7cc\Iterator\ExtensionFilteringRecursiveIterator->getChildren() /home/vagrant/php7cc/src/Infrastructure/PHP7CCCommand.php:78
PHP   9. RecursiveFilterIterator->getChildren() /home/vagrant/php7cc/src/Iterator/ExtensionFilteringRecursiveIterator.php:39
PHP  10. Sstalle\php7cc\Iterator\ExtensionFilteringRecursiveIterator->__construct() /home/vagrant/php7cc/src/Iterator/ExtensionFilteringRecursiveIterator.php:39

```

### My environment:

PHP Version => 5.3.10-1ubuntu3.14

System => Linux utrip 3.2.0-69-generic-pae #103-Ubuntu SMP Tue Sep 2 05:15:53 UTC 2014 i686
Build Date => Sep  4 2014 07:13:00
Server API => Command Line Interface
Virtual Directory Support => disabled
Configuration File (php.ini) Path => /etc/php5/cli
Loaded Configuration File => /etc/php5/cli/php.ini
Scan this dir for additional .ini files => /etc/php5/cli/conf.d
Additional .ini files parsed => /etc/php5/cli/conf.d/apc.ini,
/etc/php5/cli/conf.d/curl.ini,
/etc/php5/cli/conf.d/gd.ini,
/etc/php5/cli/conf.d/mcrypt.ini,
/etc/php5/cli/conf.d/mongodb.ini,
/etc/php5/cli/conf.d/mysql.ini,
/etc/php5/cli/conf.d/mysqli.ini,
/etc/php5/cli/conf.d/pdo.ini,
/etc/php5/cli/conf.d/pdo_mysql.ini,
/etc/php5/cli/conf.d/xdebug.ini,
/etc/php5/cli/conf.d/zz-blackfire.ini

PHP API => 20090626
PHP Extension => 20090626
Zend Extension => 220090626
Zend Extension Build => API220090626,NTS
PHP Extension Build => API20090626,NTS
Debug Build => no
Thread Safety => disabled
Zend Memory Manager => enabled
Zend Multibyte Support => disabled
IPv6 Support => enabled
Registered PHP Streams => https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, zip, phar  
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, sslv3, tls
Registered Stream Filters => zlib.*, bzip2.*, convert.iconv.*, string.rot13, string.toupper, string.tolower, string.strip_tags, convert.*, consume
d, dechunk, mcrypt.*, mdecrypt.*

**Comment by Chi-teck** [comment]
Got the same issue.

**Comment by sstalle** [comment]
Thanks for your reports. Reverted part of the commit introducing ExtensionFilteringRecursiveIterator till I  have time to investigate.
