### ISSUE TITLE
Need clarification on foreach loop warning

### ISSUE THREAD

**Issue by dmitry-varennikov-eventbase** [sstalle/php7cc#100]
HI, 

I was curious what exactly "_Nested by-reference foreach loop, make sure there is no iteration over the same array_" warning mean?

**Comment by sstalle** [comment]
Hello.

There are very subtle backward incompatible changes when the array that is iterated over is modified inside the foreach loop. Here is an [example](https://3v4l.org/5enAa) that demonstrates the difference (taken from the [foreach RFC](https://wiki.php.net/rfc/php7_foreach)).

The warning is poorly worded. It should probably say something along the lines of: _"Nested by-reference foreach loop, make sure that array modifications (if any) are safe_
