### ISSUE TITLE
Use of color to indicate issue severity reduces accessibility and ability to write output to a text file.

### ISSUE THREAD

**Issue by ba66e77** [sstalle/php7cc#107]
When run, php7cc outputs error text using only color to indicate the severity.  This is an accessibility issue for those with color blindness. 

It also means that severity information is lost when the output is piped to a file.  For instance, in the following output, the first is a yellow severity and the second is a red severity but when piped there's no indication of that.

> File: /Users/.../docroot/modules/field_ui/field_ui.module
> Line 278: Function argument(s) returned by "func_get_args" might have been modified
    func_get_args();
>
>
>File: /Users/.../docroot/modules/filter/filter.api.php
> Line 205: Removed regular expression modifier "e" used
    preg_replace('|<code>(.+?)</code>|se', '[codefilter_code]$1[/codefilter_code]', $text);

**Comment by sstalle** [comment]
You are right, that's an oversight. As a temporary workaround, you can use JSON output format (`-o json` CLI option) which keeps some form of severity information when piping to a file.

**Comment by ba66e77** [comment]
I've created PR #108 to address this.
