### ISSUE TITLE
PHP Fatal error:  Cannot access private property

### ISSUE THREAD

**Issue by whitegryphon** [sstalle/php7cc#124]
I am trying to check some websites on a CentOS 5.11 server to get a preliminary idea as to how the php code would fare in an upgrade. I've tried running against various directory paths and get the following back:
```
PHP Fatal error:  Cannot access private property Sstalle\php7cc\Infrastructure\ContainerBuilder::$outputFormat in /root/.composer/vendor/sstalle/php7cc/src/Infrastructure/ContainerBuilder.php on line 210
```
This is what I'm working with:
```
# php7cc -V
PHP 7 Compatibility Checker version 1.2.0
```
```
# php --version
PHP 5.3.3 (cli) (built: Oct 23 2014 07:48:18)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
```

I'm not familiar enough with php to figure out the issue. Let me know if I need to provide any more information. Thanks.

**Comment by sstalle** [comment]
I've released a new version (1.2.1) with the fix, please update your installation.

PS: You should take output of this tool with a grain of salt. Even if it produces a long list of warnings, it does not mean that you'll experience any problems with your websites after the upgrade. Conversely, if it says that everything is ok, it does not mean that your websites will actually work on PHP 7+.
