### ISSUE TITLE
Would you accept some help on this project?

### ISSUE THREAD

**Issue by pyrech** [sstalle/php7cc#14]
Hi :)

You did an amazing work with this project! I also developed a similar tool ([php7-checker](https://github.com/jolicode/php7-checker/)). When I started it, the goal was mainly to give a try to the PhpParser project and it was some fun to do it.

Sadly, I didn't find your library before I started mine. But as your library is far more advanced, I propose to deprecate my project in favor of yours. Would you accept some help on php7cc? I can already see some improvements that could be done like:
- increase list of functions removed
- improve the console output (with some colors fe).

**Comment by sstalle** [comment]
Hello, @pyrech. Thank you for your interest.

Sure, any help is always appreciated. There are no "official" contributing guidelines currently, but please format the code according to PSR2. If you are adding something non-trivial, it would be great if you could also write tests for it.

For relatively minor features and impovements like you've listed in your original post, you can submit pull requests directly. If you are planning on doing something that requires a lot of changes and/or big refactoring, please open an issue first so we can discuss it.

**Comment by pyrech** [comment]
Ok, cool, thanks. I will try to do some small fixes this weekend ;)
