### ISSUE TITLE
Backward incompatible changes for PHP7 too few function arguments are not detected  

### ISSUE THREAD

**Issue by pramodwerea** [sstalle/php7cc#141]
I noticed, when I run php7cc on my project folder Backward incompatible changes for PHP 7 "too few function arguments are not detected ".  Is there way to find list of functions in my project which has incompatible functions with mismatch number of arguments.

**Comment by sstalle** [comment]
It seems there has been a warning for calling a function with too few arguments for a very long time, it just had been promoted to an exception in PHP 7.1. Unfortunately, php7cc does not check for BC breaks introduced in 7.1 at the moment.

**Comment by pramodwerea** [comment]
@sstalle thank you for your feedback, will give a try to analyzer that you have mentioned.

**Comment by pramodwerea** [comment]
@sstalle for me phpstan works for me. Thanks!
