### ISSUE TITLE
Continuous integration

### ISSUE THREAD

**Issue by pyrech** [sstalle/php7cc#16]
Just wondering if you planned to setup a CI service (like travis, circle or scrutinizer fe) to run tests for PR / commits?

**Comment by sstalle** [comment]
Yes, I plan to setup Travis after completing these 2 tasks:
1. Implementing a mechanism for specifiyng minimal required PHP version for functional tests. Something like PHPUnit's `@require`. 
2. Making the project fully compatible with PHP 7. Right now some checkers (IndirectVariableOrMethodAccessVisitor, GlobalVariableVariableVisitor) rely on particular AST structure, which will probably be different on PHP 7.
