### ISSUE TITLE
New functions added

### ISSUE THREAD

**Issue by pyrech** [sstalle/php7cc#31]
In my PHP7Checker, I also added a checker that looks for redeclaration of functions whose was added in PHP7:

- random_bytes
- random_int
- error_clear_last
- gmp_random_seed
- intdiv
- preg_replace_callback_array
- posix_setrlimit
- inflate_add
- deflate_add
- inflate_init
- deflate_init

I'm not sure whether it's really pertinent but if you think so, I could port the visitor to php7cc

**Comment by sstalle** [comment]
Yes, I think it would be great. :+1:
