### ISSUE TITLE
First stable release

### ISSUE THREAD

**Issue by sstalle** [sstalle/php7cc#32]
Add warnings for the following:
- [x] [Redeclaring newly added functions](https://github.com/sstalle/php7cc/issues/31)
- [x] [Division & modulo by zero](https://github.com/tpunt/PHP7-Reference#changes-to-division-by-zero-semantics)
- [x] [```session_set_save_handler``` calls](https://wiki.php.net/rfc/session.user.return-value)

Other tasks:
- [x] Add exectable shell script (```#!/usr/bin/env php ...```)
- [x] Switch to ```Lexer\Emulative```?
- [x] Configure Travis to build & upload ```.phar``` packages to Github releases page
- [x] Update installation documentation

**Comment by sstalle** [comment]
@pyrech, do you want to add anything?

**Comment by pyrech** [comment]
It looks good to me. Redeclaring new functions will be the last missing checks of php7cc over my checker :)

**Comment by pyrech** [comment]
:clap: Nice work so far :smile:
