### ISSUE TITLE
php7cc docker image

### ISSUE THREAD

**Issue by ypereirareis** [sstalle/php7cc#53]
Hi !

I didn't really know where to give you this information....
But I created a docker image to run php7cc.

You can find it there https://github.com/ypereirareis/docker-php7cc OR there https://hub.docker.com/r/ypereirareis/php7cc/ and maybe share the information in your documentation :smiley: 

(The travis build is currently running for the first time in case you see the badge before the end of the build :smile_cat: )

Thx for your work !

**Comment by sstalle** [comment]
Thank you, @ypereirareis. I've added a note to the installation documentation
