### ISSUE TITLE
Memory Issues

### ISSUE THREAD

**Issue by andreimavenhut** [sstalle/php7cc#58]
I ran on a few files, and i got this error:
```
Fatal error: Allowed memory size of 36700160 bytes exhausted (tried to allocate 72 bytes) in /root/.composer/vendor/sstalle/php7cc/src/Token/TokenCollection.php on line 18

Call Stack:
    0.0001     221280   1. {main}() /root/.composer/vendor/sstalle/php7cc/bin/php7cc:0
    0.0003     227112   2. require('/root/.composer/vendor/sstalle/php7cc/bin/php7cc.php') /root/.composer/vendor/sstalle/php7cc/bin/php7cc:4
    0.0112    1670272   3. Symfony\Component\Console\Application->run() /root/.composer/vendor/sstalle/php7cc/bin/php7cc.php:21
    0.0135    2026696   4. Symfony\Component\Console\Application->doRun() /root/.composer/vendor/symfony/console/Application.php:123
    0.0136    2027488   5. Symfony\Component\Console\Application->doRunCommand() /root/.composer/vendor/symfony/console/Application.php:192
    0.0136    2028088   6. Symfony\Component\Console\Command\Command->run() /root/.composer/vendor/symfony/console/Application.php:844
    0.0140    2032432   7. Sstalle\php7cc\Infrastructure\PHP7CCCommand->execute() /root/.composer/vendor/symfony/console/Command/Command.php:259
    0.0333    5421656   8. Sstalle\php7cc\PathCheckExecutor->check() /root/.composer/vendor/sstalle/php7cc/src/Infrastructure/PHP7CCCommand.php:76
    0.0338    5469104   9. Sstalle\php7cc\PathChecker->check() /root/.composer/vendor/sstalle/php7cc/src/PathCheckExecutor.php:35
   11.0865   30588584  10. Sstalle\php7cc\PathChecker->checkFile() /root/.composer/vendor/sstalle/php7cc/src/PathChecker.php:48
   11.0866   30593168  11. Sstalle\php7cc\ContextChecker->checkContext() /root/.composer/vendor/sstalle/php7cc/src/PathChecker.php:63
   11.2009   32747280  12. Sstalle\php7cc\NodeTraverser\Traverser->traverse() /root/.composer/vendor/sstalle/php7cc/src/ContextChecker.php:50
   11.4681   35558448  13. Sstalle\php7cc\Token\TokenCollection->__construct() /root/.composer/vendor/sstalle/php7cc/src/NodeTraverser/Traverser.php:21
```

**Comment by vingiarrusso** [comment]
Thank you, I'm having this problem as well.

**Comment by sstalle** [comment]
@andreimavenhut @vingiarrusso Can you please check out the code from the [memory-issues](https://github.com/sstalle/php7cc/tree/memory-issues) branch and try again? It should require considerably less memory.

**Comment by vingiarrusso** [comment]
@sstalle  It worked much better on that branch.  I still hit the memory limit but it went significantly farther than before.  Will look into your suggestion.  Fantastic tool you've created, thanks again!

**Comment by sstalle** [comment]
@vingiarrusso Is the project you are trying to check public? Can you provide a link to it so that I can try to investigate further?

**Comment by seansan** [comment]
Confirmed. We see this too. PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 134217728 bytes) in phar:///php7cc.phar/src/Token/TokenCollection.php on line 18

**Comment by sstalle** [comment]
@seansan Did you try the code from the current master branch?

**Comment by acs-ferreira** [comment]
@sstalle tried current master branch, error stills triggering.
Installed by composer.

**Comment by BrandonShar** [comment]
easy fix for me was just to manually set a higher memory limit in the executable file (php7cc/bin/php7cc).  Worked great running in the root folder of my fairly large project after that.

**Comment by sstalle** [comment]
Some more improvements reducing memory usage have been made. 90% of memory is consumed by PHP-Parser on an average run now, and I don't think that its memory usage can be brought down significantly. I think that current memory handling is efficient enough, as checking 14024 files requires 69.2 MB of memory, as reported by Blackfire:
```
Checked 14024 files in 1397.730 seconds

Blackfire Run completed
 Profile URL:  https://blackfire.io/profiles/...
  Total time:  23 min 18 s
    CPU time:  22 min 48 s
         I/O:       30.2 s
      Memory:      69.2 MB
     Network:          n/a
```

I've also added a note about increasing memory limit to readme in case someone needs that.
