### ISSUE TITLE
Stub: Make a note in the README about where you can download a .phar file. 

### ISSUE THREAD

**Issue by andrewhowdencom** [sstalle/php7cc#61]
It wasn't immediately obvious for users unfamilar with GitHub. 

This is a stub. I'll submit a pull later!

**Comment by sstalle** [comment]
There is a link to the releases page in the README.md:
![readme.md image](http://i.imgur.com/2x6GQcQ.jpg)
Do you think 1 more is needed?

**Comment by andrewhowdencom** [comment]
Bizarre. Thanks for taking the time to look at this, and sorry for wasting it. I could swear both I and a colleague missed that! 

Cheers.
