### ISSUE TITLE
Respecify minimum version dependency

### ISSUE THREAD

**Issue by NicoHaase** [sstalle/php7cc#62]
Since #9, the minimum requirement for php7cc seems to be PHP 5.5.9 due to the dependency to symfony/expression-language, which requires PHP >= 5.5.9

**Comment by sstalle** [comment]
I don't think that php7cc depends on the `symfony/expression-language`. Running `composer update --prefer-lowest --no-dev` against the current master branch yields the following list of installed packages for me:

>  - Installing symfony/console (v2.3.0)
>   Loading from cache
>
>  - Installing pimple/pimple (v3.0.0)
>    Loading from cache
>
>  - Installing nikic/php-parser (v1.4.0)
>    Loading from cache

There is no `symfony/expression-language` in this list.

**Comment by gisostallenberg** [comment]
I can confirm this.

**Comment by NicoHaase** [comment]
Sorry for putting up this issue - my local composer must have had some hickups....
