### ISSUE TITLE
Uppercase letters

### ISSUE THREAD

**Issue by natertec** [sstalle/php7cc#63]
Hi,

I like your tool and it works fine so far. But it seems that it is not able to detect removed functions written in uppercase letters (I don't know why someone would do this, but the developer did this in the project I have to upgrade).

For example: mysql_connect() is recognized, MYSQL_CONNECT() is not.

Is there any workaround I could try? Thanks for any suggestions.

**Comment by sstalle** [comment]
Thank you for your report, @natertec. The master branch was updated to detect removed function names in any case.
