### ISSUE TITLE
relative file names?

### ISSUE THREAD

**Issue by onlyjob** [sstalle/php7cc#67]
`php7cc` print full file names in `File: ` field even if I invoke checker from current directory like `php7cc .`.
It would be great if _php7cc_ could report file names with relative paths from current directory instead of full paths from root. This would be helpful to report PHP-7 incompatibilities upstream without cluttering _php7cc_ output with meaningless local paths to current working directory.

Thanks.

**Comment by sstalle** [comment]
This can now be done using the ```--relative-paths (-r)``` command line option.

**Comment by onlyjob** [comment]
Great, thanks! :)
