### ISSUE TITLE
PHP-7 compatible dependencies?

### ISSUE THREAD

**Issue by onlyjob** [sstalle/php7cc#69]
While I was [working on packaging of _php7cc_](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=820420) to introduce it to [Debian](http://debian.org) it came to my attention that _php-pimple_ (direct dependency of _php7cc_) is [not compatible with PHP-7](https://github.com/silexphp/Pimple/issues/184).
Debian is dropping PHP-5 so I wonder if _php7cc_ could switch to PHP-7 compatible alternative of Pimple? The latter FTBFS with PHP-7...

**Comment by sstalle** [comment]
I'm not familiar with the Debian packaging process. Why does it require building the Pimple C extension from source? Why isn't the pure PHP implementation sufficient?

**Comment by onlyjob** [comment]
Everything is built from source in Debian. Please forgive my PHP illiteracy but I don't know whether pure PHP implementation is sufficient. I suppose that would be question to maintainer or to Pumple developer(s)...

**Comment by sstalle** [comment]
Pimple has 2 independent interchangeable implementations: the pure PHP one and the C extension. The latter, which is incompatible with PHP 7, can be used in environments having high performance requirements, but it is completely optional. The former, on the other hand, seems to be compatible with PHP 7. Its tests pass on PHP 7.0.6-dev. And php7cc only depends on the pure PHP implementation. In fact, it was never even tested against the C extension. So I don't see why a dependency on Pimple is an issue.

**Comment by onlyjob** [comment]
Thank you for explanation. Pimple is currently an issue because it FTBFS (at least its C extension part). I'll see if I can address that...

**Comment by onlyjob** [comment]
Thanks again for helpful hints. For now we won't build Pimple C extension due to incompatibilities with PHP-7. Pimple class seems OK and that should do as _php7cc_ dependency. :)
