### ISSUE TITLE
Add an except option

### ISSUE THREAD

**Issue by nWidart** [sstalle/php7cc#7]
Hello,

Let me start by saying this looks like a very nice tool.
It would be nice to have an 'except' option, to ignore certain folders (ie vendor).

**Comment by sstalle** [comment]
Thank you for your suggestion, @nWidart. You can now use command line option --except or -x to achieve what you want. For example, to ignore ```/path/to/your/project/vendor``` dir:
```bash
php7cc bin/php7cc.php -x vendor /path/to/your/project
```

**Comment by nWidart** [comment]
Awesome! Thank you :)
