### ISSUE TITLE
PHP Fatal error:  'continue' not in the 'loop' or 'switch' context

### ISSUE THREAD

**Issue by yamlfd** [sstalle/php7cc#89]
PHP 7 compatibility checks are not working well, see https://www.drupal.org/node/2760025

[Sun Jul 03 22:59:57.311158 2016] [:error] [pid 3168:tid 1844] [client ::1:54149] PHP Fatal error:  'continue' not in the 'loop' or 'switch' context in httprl\\httprl.module on line 1418

Drupal 7 code can be found at https://www.drupal.org/project/httprl.

**Comment by sstalle** [comment]
Thank you for your report, @yamlfd. It would help a lot if you could provide the exact code you are running, because I don't see any `continue` statements on line 1418 of the most recent development release of `httprl.module` from https://www.drupal.org/project/httprl

**Comment by yamlfd** [comment]
See http://cgit.drupalcode.org/httprl/tree/httprl.module?h=7.x-1.x

**Comment by sstalle** [comment]
Check for `continue` outside loop was added to the master branch. I tried running it against the http://cgit.drupalcode.org/httprl/tree/httprl.module?h=7.x-1.x, but it did not produce any warnings. I also tried native PHP syntax checking:
```
$ php -v
PHP 7.0.10-dev (cli) (built: Jul  5 2016 17:02:11) ( NTS DEBUG )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.10-dev, Copyright (c) 1999-2016, by Zend Technologies
$ php -l httprl.module
No syntax errors detected in httprl.module
```

Please feel free to reopen if you can provide a failing test case.

**Comment by yamlfd** [comment]
I tried your _PHP 7 Compatibility Checker version 1.1.0_ agains the last release https://ftp.drupal.org/files/projects/httprl-7.x-1.14.zip and it complained.

**Comment by yamlfd** [comment]
Ah, sorry - confusend myself... your checker does NOT complain. That is the bug. PHP itself complains if it includes the httprl module in Drupal.

>php -l httprl.module
No syntax errors detected in httprl.module

This also gives me no info, but if the module is enabled in Drupal - PHP stops with an exception.
