### ISSUE TITLE
Use symfony 2.7.x

### ISSUE THREAD

**Issue by nWidart** [sstalle/php7cc#9]
Hello,

I would like to install this using `composer global require sstalle/php7cc`, instead of having to create a project for it.
This would allow me to run `php7cc` from anywhere.

Only problem is that it requires an old version of Symfony (`2.5.x`) which causes conflicts with other global packages that are requiring `2.7.x`.

Could the dependency be updated safely here ? Or is there any specific reason `2.5.x` is uses ?

Thanks

**Comment by sstalle** [comment]
Hello, @nWidart. I've made ```symfony/console``` version constraint less strict. I think ```php7cc``` should coexist along with ```2.7``` just fine now. If it does not, please feel free to reopen the issue.

The reason ```2.5``` was used (and now ```2.3```) is that it required lower ```php``` version than ```2.7```.

**Comment by pavarnos** [comment]
hi. any chance of using symfony/console 3.0 or above? i'm having related problems similar to @nWidart.

**Comment by pyrech** [comment]
Indeed, php7cc could require symfony/console with constraint `~2.3|~3.0` and we could update travis to make one build installing vendors with `--prefer-lowest` (although there is no tests for cli result I think).

**Comment by pavarnos** [comment]
thanks. keen to try it out but both my project and my global install require 3.0 or above

**Comment by pyrech** [comment]
Alternatively you could also install it via the PHAR method (see the Readme) :wink:

**Comment by sstalle** [comment]
`composer.json` was updated in the master branch. I think `symfony/console 3.0` should not be a problem now.
