### ISSUE TITLE
PHP Fatal error:  Maximum function nesting level of '100' reached

### ISSUE THREAD

**Issue by codex8** [sstalle/php7cc#93]
**When i run Php 7 comparability test on my wordpress plugin im getting this error.** 

`PHP Fatal error:  Maximum function nesting level of '100' reached, aborting! in /var/www/html/test/vendor/sstalle/php7cc/src/NodeAnalyzer/FunctionAnalyzer.php on line 15
PHP Stack trace:
PHP   1. {main}() /var/www/html/test/vendor/sstalle/php7cc/bin/php7cc:0
PHP   2. require() /var/www/html/test/vendor/sstalle/php7cc/bin/php7cc:4
PHP   3. Symfony\Component\Console\Application->run() /var/www/html/test/vendor/sstalle/php7cc/bin/php7cc.php:21
PHP   4. Symfony\Component\Console\Application->doRun() /var/www/html/test/vendor/symfony/console/Application.php:117
PHP   5. Symfony\Component\Console\Application->doRunCommand() /var/www/html/test/vendor/symfony/console/Application.php:186
PHP   6. Symfony\Component\Console\Command\Command->run() /var/www/html/test/vendor/symfony/console/Application.php:818
PHP   7. Sstalle\php7cc\Infrastructure\PHP7CCCommand->execute() /var/www/html/test/vendor/symfony/console/Command/Command.php:256
PHP   8. Sstalle\php7cc\PathCheckExecutor->check() /var/www/html/test/vendor/sstalle/php7cc/src/Infrastructure/PHP7CCCommand.php:128
PHP   9. Sstalle\php7cc\PathChecker->check() /var/www/html/test/vendor/sstalle/php7cc/src/PathCheckExecutor.php:65
PHP  10. Sstalle\php7cc\PathChecker->checkFile() /var/www/html/test/vendor/sstalle/php7cc/src/PathChecker.php:41
PHP  11. Sstalle\php7cc\ContextChecker->checkContext() /var/www/html/test/vendor/sstalle/php7cc/src/PathChecker.php:57
PHP  12. Sstalle\php7cc\NodeTraverser\Traverser->traverse() /var/www/html/test/vendor/sstalle/php7cc/src/ContextChecker.php:50
PHP  13. PhpParser\NodeTraverser->traverse() /var/www/html/test/vendor/sstalle/php7cc/src/NodeTraverser/Traverser.php:28
PHP  14. PhpParser\NodeTraverser->traverseArray() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:64
PHP  15. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  16. PhpParser\NodeTraverser->traverseArray() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
PHP  17. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  18. PhpParser\NodeTraverser->traverseArray() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
PHP  19. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  20. PhpParser\NodeTraverser->traverseArray() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:84
PHP  21. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:129
PHP  22. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  23. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  24. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  25. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  26. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  27. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  28. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  29. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  30. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  31. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  32. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  33. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  34. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  35. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  36. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  37. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  38. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  39. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  40. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  41. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  42. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  43. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  44. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  45. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  46. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  47. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  48. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  49. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  50. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  51. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  52. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  53. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  54. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  55. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  56. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  57. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  58. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  59. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  60. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  61. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  62. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  63. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  64. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  65. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  66. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  67. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  68. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  69. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  70. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  71. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  72. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  73. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  74. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  75. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  76. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  77. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  78. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  79. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  80. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  81. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  82. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  83. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  84. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  85. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  86. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  87. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  88. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  89. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  90. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  91. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  92. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  93. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  94. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  95. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  96. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  97. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  98. PhpParser\NodeTraverser->traverseNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:97
PHP  99. Sstalle\php7cc\NodeVisitor\RemovedFunctionCallVisitor->enterNode() /var/www/html/test/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php:88
`

**Comment by sstalle** [comment]
Have you tried updating `xdebug.max_nesting_level` to a higher value as described in the [Troubleshooting](https://github.com/sstalle/php7cc#user-content-troubleshooting) section of the readme file?

**Comment by codex8** [comment]
yeah just did it and it's working now thanks :+1:  @sstalle
