### ISSUE TITLE
JSON output

### ISSUE THREAD

**Issue by timnashcouk** [sstalle/php7cc#96]
It would be really handy, to be able to do something with the returned output, in its current form while not impossible to awk and manipulate it. Would be ideal to have the output as a JSON optionally to be able to parse into other applications.

**Comment by marcovtwout** [comment]
+1 for more output formats.

I made a quick and dirty version of a CSV output, where every error message is rendered into one line: https://gist.github.com/marcovtwout/129d1ef5b17eca0d7ade89e4d55da360

![image](https://cloud.githubusercontent.com/assets/438046/20142591/a1fd2896-a695-11e6-98c9-2e24e0559454.png)

**Comment by vanbogaertjonas** [comment]
Where is the output going? 
Unable to find it
Thanks in advance
