### ISSUE TITLE
Add support for PHP 7.1

### ISSUE THREAD

**Issue by vincentchalamon** [sstalle/php7cc#99]
[PHP 7.1 is stable since December 1st](http://php.net/archive/2016.php#id2016-12-01-3), and gives a lot of enhancements. I.e., it allows to add a `?` on method return type to allow null or type (`?string`).

php7cc ran on a PHP7.1 project throw following errors:
```bash
> Syntax error, unexpected '?' on line 22. Processing aborted.
```

**Comment by sstalle** [comment]
It's the same issue as https://github.com/sstalle/php7cc/issues/79. php7cc needs to be upgraded to use PHP-Parser 3. Unfortunately I can't dedicate much time to this project now and I can't give an ETA, but I'm open to pull requests.

**Comment by vincentchalamon** [comment]
Duplicate from #79
